name: GitHub Actions Demo
on: [pull_request]
jobs:
  Basic-CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
      - name: Build test image
        run: |
          docker build -t test-image --target test .
      - name: Run unit and integration tests
        run: |
          docker run --env-file=.env.test test-image todo_app
      - name: Run end to end tests
        run: |
          docker run \
          -e SECRET_KEY=secret \
          -e TRELLO_SERVER_TOKEN=${{ secrets.TRELLO_SERVER_TOKEN }} \
          -e TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }} \
          -e TRELLO_WORKSPACE_ID=${{ secrets.TRELLO_WORKSPACE_ID }} \
          test-image tests_e2e
      - run: echo "This job's status is ${{ job.status }}."
